project_id = "tcmyidycqdrrtwuaovbk"

[functions.isochrone]
verify_jwt = false

[functions.isochrone-insights]
verify_jwt = false

[functions.poi-insights]
verify_jwt = false

[functions.sync-uf-values]
verify_jwt = true

[functions.compute-poi-features]
verify_jwt = true
